artifacts_config:
  artifacts_dir: artifacts_config:

data_ingestion_config:
  dataset_doenload_url: https://github.com/anulsasidharan/raw_datasets/blob/main/books-data.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data